/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.awt.Color;
import javax.swing.BorderFactory;
import utility.bdutility;

/**
 *
 * @author NEHA MAITY
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
        bdutility.setImage(this, "images/hellobg.jpg",1500,1000);
        this.getRootPane().setBorder(BorderFactory.createMatteBorder(4,4,4,4, Color.black));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExit = new javax.swing.JButton();
        btnviewdetails = new javax.swing.JButton();
        btnnewregistration = new javax.swing.JButton();
        btnupdatedetails = new javax.swing.JButton();
        btnDeleteDetails = new javax.swing.JButton();
        btngenerateQr = new javax.swing.JButton();
        btnViewQr = new javax.swing.JButton();
        btnMarkAttendance = new javax.swing.JButton();
        btnViewAttendance = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1500, 1000));
        setMinimumSize(new java.awt.Dimension(1500, 1000));
        setUndecorated(true);

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExit.setText("X");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnviewdetails.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnviewdetails.setText("View Deatils");
        btnviewdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewdetailsActionPerformed(evt);
            }
        });

        btnnewregistration.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnnewregistration.setText("New Registration");
        btnnewregistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewregistrationActionPerformed(evt);
            }
        });

        btnupdatedetails.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnupdatedetails.setText("Update Details");
        btnupdatedetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdatedetailsActionPerformed(evt);
            }
        });

        btnDeleteDetails.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnDeleteDetails.setText("Delete Details");

        btngenerateQr.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btngenerateQr.setText("Generate Qr");
        btngenerateQr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngenerateQrActionPerformed(evt);
            }
        });

        btnViewQr.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnViewQr.setText("View Qr");
        btnViewQr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewQrActionPerformed(evt);
            }
        });

        btnMarkAttendance.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnMarkAttendance.setText("Mark Attendance");
        btnMarkAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarkAttendanceActionPerformed(evt);
            }
        });

        btnViewAttendance.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnViewAttendance.setText("View Attendance");
        btnViewAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAttendanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnnewregistration, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnviewdetails)
                .addGap(43, 43, 43)
                .addComponent(btnupdatedetails)
                .addGap(44, 44, 44)
                .addComponent(btnDeleteDetails)
                .addGap(44, 44, 44)
                .addComponent(btngenerateQr)
                .addGap(45, 45, 45)
                .addComponent(btnViewQr)
                .addGap(46, 46, 46)
                .addComponent(btnMarkAttendance)
                .addGap(39, 39, 39)
                .addComponent(btnViewAttendance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnviewdetails, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnupdatedetails, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btngenerateQr, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnnewregistration, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewQr, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMarkAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1040, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnnewregistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewregistrationActionPerformed
        // TODO add your handling code here:
        bdutility.openForm(newregistration.class.getSimpleName(), new newregistration());
    }//GEN-LAST:event_btnnewregistrationActionPerformed

    private void btnviewdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewdetailsActionPerformed
        // TODO add your handling code here:
        bdutility.openForm(viewdetails.class.getSimpleName(), new viewdetails());
    }//GEN-LAST:event_btnviewdetailsActionPerformed

    private void btnupdatedetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdatedetailsActionPerformed
        // TODO add your handling code here:
        bdutility.openForm(updatedetails.class.getSimpleName(),new updatedetails());
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnupdatedetailsActionPerformed

    private void btngenerateQrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenerateQrActionPerformed
        // TODO add your handling code here:
        bdutility.openForm(GenerateQr.class.getSimpleName(), new GenerateQr());
    }//GEN-LAST:event_btngenerateQrActionPerformed

    private void btnViewQrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewQrActionPerformed
        // TODO add your handling code here:
        bdutility.openForm(viewqr.class.getSimpleName(), new viewqr());
    }//GEN-LAST:event_btnViewQrActionPerformed

    private void btnMarkAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarkAttendanceActionPerformed
        // TODO add your handling code here:
        bdutility.openForm(markattendance.class.getSimpleName(), new markattendance());
    }//GEN-LAST:event_btnMarkAttendanceActionPerformed

    private void btnViewAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAttendanceActionPerformed
        // TODO add your handling code here:
        bdutility.openForm(viewattandance.class.getSimpleName(), new viewattandance());
    }//GEN-LAST:event_btnViewAttendanceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteDetails;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnMarkAttendance;
    private javax.swing.JButton btnViewAttendance;
    private javax.swing.JButton btnViewQr;
    private javax.swing.JButton btngenerateQr;
    private javax.swing.JButton btnnewregistration;
    private javax.swing.JButton btnupdatedetails;
    private javax.swing.JButton btnviewdetails;
    // End of variables declaration//GEN-END:variables
}
